import '../../features/events/domain/entities/event.dart';

class LocalDataService {
  static List<EventEntity> getSampleEvents() {
    return [
      EventEntity(
        eventId: 'event_001',
        title: 'Morning Yoga Session',
        description: 'Start your day with a peaceful yoga session in the park. Perfect for all fitness levels, from beginners to advanced practitioners. Bring your own mat and water bottle.',
        date: DateTime.now().add(const Duration(days: 2)),
        location: 'Central Park, New York',
        imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        createdBy: 'admin',
        rsvps: ['user1', 'user2', 'user3'],
        sportType: 'Yoga',
        difficultyLevel: 'Beginner',
        maxParticipants: 20,
        equipment: 'Yoga mat, water bottle',
        duration: '1 hour',
      ),
      EventEntity(
        eventId: 'event_002',
        title: 'Basketball Tournament',
        description: 'Join our competitive basketball tournament! Teams of 5 players each. Prizes for winners. All skill levels welcome. Bring your A-game!',
        date: DateTime.now().add(const Duration(days: 7)),
        location: 'Madison Square Garden, New York',
        imageUrl: 'https://images.unsplash.com/photo-1546519638-68e10945ff9e?w=800&h=600&fit=crop',
        createdBy: 'admin',
        rsvps: ['user1', 'user4', 'user5'],
        sportType: 'Basketball',
        difficultyLevel: 'Intermediate',
        maxParticipants: 40,
        equipment: 'Basketball shoes, water bottle',
        duration: '3 hours',
      ),
      EventEntity(
        eventId: 'event_003',
        title: '5K Fun Run',
        description: 'Join us for a fun 5K run through the city! Perfect for runners of all levels. Water stations provided. Medals for all participants.',
        date: DateTime.now().add(const Duration(days: 15)),
        location: 'Prospect Park, Brooklyn',
        imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        createdBy: 'admin',
        rsvps: ['user1', 'user2', 'user3', 'user4', 'user5'],
        sportType: 'Running',
        difficultyLevel: 'Beginner',
        maxParticipants: 100,
        equipment: 'Running shoes, water bottle',
        duration: '1.5 hours',
      ),
      EventEntity(
        eventId: 'event_004',
        title: 'CrossFit Bootcamp',
        description: 'High-intensity CrossFit workout for all fitness levels. Build strength, endurance, and community. No experience necessary!',
        date: DateTime.now().add(const Duration(days: 20)),
        location: 'CrossFit Manhattan',
        imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        createdBy: 'admin',
        rsvps: ['user2', 'user6'],
        sportType: 'CrossFit',
        difficultyLevel: 'Intermediate',
        maxParticipants: 15,
        equipment: 'Workout clothes, water bottle',
        duration: '1 hour',
      ),
      EventEntity(
        eventId: 'event_005',
        title: 'Tennis Tournament',
        description: 'Competitive tennis tournament for all skill levels. Singles and doubles matches. Prizes for winners!',
        date: DateTime.now().add(const Duration(days: 25)),
        location: 'Central Park Tennis Center',
        imageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&h=600&fit=crop',
        createdBy: 'admin',
        rsvps: ['user1', 'user3', 'user7'],
        sportType: 'Tennis',
        difficultyLevel: 'Intermediate',
        maxParticipants: 32,
        equipment: 'Tennis racket, tennis shoes',
        duration: '4 hours',
      ),
      EventEntity(
        eventId: 'event_006',
        title: 'Swimming Lessons',
        description: 'Learn to swim or improve your technique with certified instructors. All levels welcome from beginners to advanced.',
        date: DateTime.now().add(const Duration(days: 30)),
        location: 'NYC Aquatics Center',
        imageUrl: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&h=600&fit=crop',
        createdBy: 'admin',
        rsvps: ['user4', 'user8'],
        sportType: 'Swimming',
        difficultyLevel: 'Beginner',
        maxParticipants: 12,
        equipment: 'Swimsuit, towel, goggles',
        duration: '1 hour',
      ),
      EventEntity(
        eventId: 'event_007',
        title: 'Rock Climbing Session',
        description: 'Indoor rock climbing for all skill levels. Equipment provided. Learn basic techniques and safety procedures.',
        date: DateTime.now().add(const Duration(days: 35)),
        location: 'Brooklyn Boulders',
        imageUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&h=600&fit=crop',
        createdBy: 'admin',
        rsvps: ['user2', 'user5', 'user9'],
        sportType: 'Rock Climbing',
        difficultyLevel: 'Beginner',
        maxParticipants: 20,
        equipment: 'Climbing shoes (rental available)',
        duration: '2 hours',
      ),
      EventEntity(
        eventId: 'event_008',
        title: 'Cycling Group Ride',
        description: 'Scenic cycling tour through the city. Explore bike paths and enjoy the outdoors. Helmets required.',
        date: DateTime.now().add(const Duration(days: 40)),
        location: 'Hudson River Greenway',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=600&fit=crop',
        createdBy: 'admin',
        rsvps: ['user1', 'user6', 'user10'],
        sportType: 'Cycling',
        difficultyLevel: 'Beginner',
        maxParticipants: 25,
        equipment: 'Bicycle, helmet, water bottle',
        duration: '2 hours',
      ),
    ];
  }
}
