import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';

void main() async {
  print('Starting FitPulse Firestore population script...');
  
  try {
    // Initialize Firebase
    await Firebase.initializeApp();
    print('Firebase initialized successfully');
    
    final firestore = FirebaseFirestore.instance;
    
    // Sample sports and fitness events data with public image URLs
    final events = [
      {
        'eventId': 'event_001',
        'title': 'Morning Yoga Session',
        'description': 'Start your day with a peaceful yoga session in the park. Perfect for all fitness levels, from beginners to advanced practitioners. Bring your own mat and water bottle.',
        'date': DateTime.now().add(const Duration(days: 2)).toIso8601String(),
        'location': 'Central Park, New York',
        'imageUrl': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user1', 'user2', 'user3'],
        'sportType': 'Yoga',
        'difficultyLevel': 'Beginner',
        'maxParticipants': 20,
        'equipment': 'Yoga mat, water bottle',
        'duration': '1 hour',
      },
      {
        'eventId': 'event_002',
        'title': 'Basketball Tournament',
        'description': 'Join our competitive basketball tournament! Teams of 5 players each. Prizes for winners. All skill levels welcome. Bring your A-game!',
        'date': DateTime.now().add(const Duration(days: 7)).toIso8601String(),
        'location': 'Madison Square Garden, New York',
        'imageUrl': 'https://images.unsplash.com/photo-1546519638-68e10945ff9e?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user1', 'user4', 'user5'],
        'sportType': 'Basketball',
        'difficultyLevel': 'Intermediate',
        'maxParticipants': 40,
        'equipment': 'Basketball shoes, water bottle',
        'duration': '3 hours',
      },
      {
        'eventId': 'event_003',
        'title': '5K Fun Run',
        'description': 'Join us for a fun 5K run through the city! Perfect for runners of all levels. Water stations provided. Medals for all participants.',
        'date': DateTime.now().add(const Duration(days: 15)).toIso8601String(),
        'location': 'Prospect Park, Brooklyn',
        'imageUrl': 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user1', 'user2', 'user3', 'user4', 'user5'],
        'sportType': 'Running',
        'difficultyLevel': 'Beginner',
        'maxParticipants': 100,
        'equipment': 'Running shoes, water bottle',
        'duration': '1.5 hours',
      },
      {
        'eventId': 'event_004',
        'title': 'CrossFit Bootcamp',
        'description': 'High-intensity CrossFit workout for all fitness levels. Build strength, endurance, and community. No experience necessary!',
        'date': DateTime.now().add(const Duration(days: 20)).toIso8601String(),
        'location': 'CrossFit Manhattan',
        'imageUrl': 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user2', 'user6'],
        'sportType': 'CrossFit',
        'difficultyLevel': 'Intermediate',
        'maxParticipants': 15,
        'equipment': 'Workout clothes, water bottle',
        'duration': '1 hour',
      },
      {
        'eventId': 'event_005',
        'title': 'Tennis Tournament',
        'description': 'Competitive tennis tournament for all skill levels. Singles and doubles matches. Prizes for winners!',
        'date': DateTime.now().add(const Duration(days: 25)).toIso8601String(),
        'location': 'Central Park Tennis Center',
        'imageUrl': 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user1', 'user3', 'user7'],
        'sportType': 'Tennis',
        'difficultyLevel': 'Intermediate',
        'maxParticipants': 32,
        'equipment': 'Tennis racket, tennis shoes',
        'duration': '4 hours',
      },
      {
        'eventId': 'event_006',
        'title': 'Swimming Lessons',
        'description': 'Learn to swim or improve your technique with certified instructors. All levels welcome from beginners to advanced.',
        'date': DateTime.now().add(const Duration(days: 30)).toIso8601String(),
        'location': 'NYC Aquatics Center',
        'imageUrl': 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user4', 'user8'],
        'sportType': 'Swimming',
        'difficultyLevel': 'Beginner',
        'maxParticipants': 12,
        'equipment': 'Swimsuit, towel, goggles',
        'duration': '1 hour',
      },
      {
        'eventId': 'event_007',
        'title': 'Rock Climbing Session',
        'description': 'Indoor rock climbing for all skill levels. Equipment provided. Learn basic techniques and safety procedures.',
        'date': DateTime.now().add(const Duration(days: 35)).toIso8601String(),
        'location': 'Brooklyn Boulders',
        'imageUrl': 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user2', 'user5', 'user9'],
        'sportType': 'Rock Climbing',
        'difficultyLevel': 'Beginner',
        'maxParticipants': 20,
        'equipment': 'Climbing shoes (rental available)',
        'duration': '2 hours',
      },
      {
        'eventId': 'event_008',
        'title': 'Cycling Group Ride',
        'description': 'Scenic cycling tour through the city. Explore bike paths and enjoy the outdoors. Helmets required.',
        'date': DateTime.now().add(const Duration(days: 40)).toIso8601String(),
        'location': 'Hudson River Greenway',
        'imageUrl': 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user1', 'user6', 'user10'],
        'sportType': 'Cycling',
        'difficultyLevel': 'Beginner',
        'maxParticipants': 25,
        'equipment': 'Bicycle, helmet, water bottle',
        'duration': '2 hours',
      },
      {
        'eventId': 'event_009',
        'title': 'Boxing Training',
        'description': 'Learn boxing fundamentals with professional trainers. Great for fitness and self-defense. All equipment provided.',
        'date': DateTime.now().add(const Duration(days: 45)).toIso8601String(),
        'location': 'Gleason\'s Gym, Brooklyn',
        'imageUrl': 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user3', 'user7'],
        'sportType': 'Boxing',
        'difficultyLevel': 'Beginner',
        'maxParticipants': 12,
        'equipment': 'Workout clothes, water bottle',
        'duration': '1 hour',
      },
      {
        'eventId': 'event_010',
        'title': 'Soccer Match',
        'description': 'Friendly soccer match for all skill levels. Teams will be balanced. Bring your cleats and competitive spirit!',
        'date': DateTime.now().add(const Duration(days: 50)).toIso8601String(),
        'location': 'Randall\'s Island Soccer Fields',
        'imageUrl': 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user4', 'user8', 'user11'],
        'sportType': 'Soccer',
        'difficultyLevel': 'Intermediate',
        'maxParticipants': 22,
        'equipment': 'Soccer cleats, shin guards',
        'duration': '1.5 hours',
      },
      {
        'eventId': 'event_011',
        'title': 'Pilates Class',
        'description': 'Strengthen your core with our Pilates class. Improve flexibility, posture, and overall body strength.',
        'date': DateTime.now().add(const Duration(days: 55)).toIso8601String(),
        'location': 'Pure Pilates Studio, Manhattan',
        'imageUrl': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user5', 'user9'],
        'sportType': 'Pilates',
        'difficultyLevel': 'Beginner',
        'maxParticipants': 15,
        'equipment': 'Yoga mat, comfortable clothes',
        'duration': '1 hour',
      },
      {
        'eventId': 'event_012',
        'title': 'Weightlifting Workshop',
        'description': 'Learn proper weightlifting techniques and form. Perfect for beginners looking to start strength training safely.',
        'date': DateTime.now().add(const Duration(days: 60)).toIso8601String(),
        'location': 'Iron Paradise Gym, Queens',
        'imageUrl': 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user6', 'user10', 'user12'],
        'sportType': 'Weightlifting',
        'difficultyLevel': 'Beginner',
        'maxParticipants': 10,
        'equipment': 'Workout clothes, water bottle',
        'duration': '1.5 hours',
      },
      {
        'eventId': 'event_013',
        'title': 'Martial Arts Training',
        'description': 'Learn self-defense and martial arts techniques. Great for fitness, discipline, and confidence building. All levels welcome.',
        'date': DateTime.now().add(const Duration(days: 65)).toIso8601String(),
        'location': 'Dojo NYC, Manhattan',
        'imageUrl': 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user7', 'user11'],
        'sportType': 'Martial Arts',
        'difficultyLevel': 'Beginner',
        'maxParticipants': 16,
        'equipment': 'Workout clothes, water bottle',
        'duration': '1.5 hours',
      },
      {
        'eventId': 'event_014',
        'title': 'HIIT Workout',
        'description': 'High-Intensity Interval Training for maximum calorie burn. Short bursts of intense exercise with rest periods. Perfect for busy schedules!',
        'date': DateTime.now().add(const Duration(days: 70)).toIso8601String(),
        'location': 'FitLife Gym, Brooklyn',
        'imageUrl': 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user8', 'user12', 'user13'],
        'sportType': 'HIIT',
        'difficultyLevel': 'Advanced',
        'maxParticipants': 20,
        'equipment': 'Workout clothes, water bottle, towel',
        'duration': '45 minutes',
      },
      {
        'eventId': 'event_015',
        'title': 'Volleyball Tournament',
        'description': 'Beach volleyball tournament on the courts. Teams of 6 players. Prizes for winners! Bring your competitive spirit.',
        'date': DateTime.now().add(const Duration(days: 75)).toIso8601String(),
        'location': 'Beach Volleyball Courts, Brooklyn',
        'imageUrl': 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&h=600&fit=crop',
        'createdBy': 'admin',
        'rsvps': ['user9', 'user14'],
        'sportType': 'Volleyball',
        'difficultyLevel': 'Intermediate',
        'maxParticipants': 24,
        'equipment': 'Volleyball shoes, water bottle',
        'duration': '3 hours',
      },
    ];

    // Sample users data with fitness profiles
    final users = [
      {
        'uid': 'user1',
        'name': 'Alex Johnson',
        'email': 'alex.johnson@example.com',
        'profilePic': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
        'bio': 'Fitness enthusiast and personal trainer. Love helping others achieve their goals!',
        'fitnessLevel': 'Advanced',
        'favoriteSports': ['Weightlifting', 'CrossFit', 'Running'],
        'workoutGoals': 'Build strength and help others get fit',
        'age': 28,
        'gender': 'Male',
      },
      {
        'uid': 'user2',
        'name': 'Sarah Chen',
        'email': 'sarah.chen@example.com',
        'profilePic': 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
        'bio': 'Yoga instructor and wellness coach. Passionate about mindfulness and movement.',
        'fitnessLevel': 'Intermediate',
        'favoriteSports': ['Yoga', 'Pilates', 'Swimming'],
        'workoutGoals': 'Maintain flexibility and inner peace',
        'age': 32,
        'gender': 'Female',
      },
      {
        'uid': 'user3',
        'name': 'Mike Rodriguez',
        'email': 'mike.rodriguez@example.com',
        'profilePic': 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
        'bio': 'Basketball player and coach. Always looking for a good game!',
        'fitnessLevel': 'Advanced',
        'favoriteSports': ['Basketball', 'Tennis', 'Soccer'],
        'workoutGoals': 'Stay competitive and improve skills',
        'age': 25,
        'gender': 'Male',
      },
      {
        'uid': 'user4',
        'name': 'Emma Wilson',
        'email': 'emma.wilson@example.com',
        'profilePic': 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
        'bio': 'Marathon runner and cycling enthusiast. Love endurance sports!',
        'fitnessLevel': 'Advanced',
        'favoriteSports': ['Running', 'Cycling', 'Swimming'],
        'workoutGoals': 'Complete a triathlon',
        'age': 30,
        'gender': 'Female',
      },
      {
        'uid': 'user5',
        'name': 'David Kim',
        'email': 'david.kim@example.com',
        'profilePic': 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
        'bio': 'Rock climbing instructor and outdoor enthusiast. Always up for an adventure!',
        'fitnessLevel': 'Intermediate',
        'favoriteSports': ['Rock Climbing', 'Hiking', 'Boxing'],
        'workoutGoals': 'Master advanced climbing techniques',
        'age': 27,
        'gender': 'Male',
      },
    ];

    print('Starting to populate Firestore with ${events.length} events and ${users.length} users...');

    // Add each event to Firestore
    for (final event in events) {
      await firestore.collection('events').doc(event['eventId'] as String).set(event);
      print('✓ Added event: ${event['title']}');
    }

    // Add each user to Firestore
    for (final user in users) {
      await firestore.collection('users').doc(user['uid'] as String).set(user);
      print('✓ Added user: ${user['name']}');
    }
    
    print('\n🎉 Successfully populated Firestore with ${events.length} events and ${users.length} users!');
    print('You can now run your Flutter app to see the real data.');
    
  } catch (e) {
    print('❌ Error populating Firestore: $e');
    exit(1);
  }
}
